# Generated by Django 3.2.9 on 2021-11-26 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerresponse',
            name='answer_request',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.answerrequest'),
            preserve_default=False,
        ),
    ]
